/* ═══════════════════════════════════════════════
   lang.js — Çoxdilli dəstək (Az / Ru / En)
   Bütün HTML fayllarına components.js-dən ƏVVƏL əlavə et:
   <script src="js/lang.js"></script>
   ═══════════════════════════════════════════════ */

const LANGS = {

  /* ══════════════ AZƏRBAYCAN ══════════════ */
  az: {
    /* Header */
    'header.search':    'Məhsul, marka və ya kateqoriya axtar...',
    'header.signin':    'Daxil ol',
    'header.wishlist':  'İstək siyahısı',
    'header.cart':      'Səbət',
    /* Hero strip */
    'strip.text':       '🚚 <span>50 AZN</span> üzərindəki sifarişlərə pulsuz çatdırılma &nbsp;|&nbsp; Yeni kolleksiya gəldi ✨',
    /* Footer */
    'footer.tagline':   'Ən yeni geyim trendlərini kəşf edin.<br>Keyfiyyət, üslub və rahatlıq.',
    'footer.cats':      'Kateqoriyalar',
    'footer.women':     'Qadın',
    'footer.men':       'Kişi',
    'footer.kids':      'Uşaq',
    'footer.acc':       'Aksesuarlar',
    'footer.help':      'Kömək',
    'footer.delivery':  'Çatdırılma',
    'footer.returns':   'Qaytarma',
    'footer.size':      'Ölçü Cədvəli',
    'footer.contact':   'Əlaqə',
    'footer.about':     'Haqqımızda',
    'footer.who':       'Biz kimik',
    'footer.careers':   'Karyera',
    'footer.privacy':   'Gizlilik',
    'footer.terms':     'Şərtlər',
    'footer.copy':      '© 2025 MODA. Bütün hüquqlar qorunur.',
    /* Auth modal */
    'auth.loginTitle':  'Xoş gəldiniz',
    'auth.regTitle':    'Qeydiyyat',
    'auth.loginSub':    'Hesabınıza daxil olun',
    'auth.regSub':      'Yeni hesab yaradın',
    'auth.name':        'Ad Soyad',
    'auth.namePh':      'Adınızı daxil edin',
    'auth.email':       'E-poçt',
    'auth.emailPh':     'ornek@mail.com',
    'auth.pass':        'Şifrə',
    'auth.passPh':      '••••••••',
    'auth.loginBtn':    'Daxil ol',
    'auth.regBtn':      'Qeydiyyatdan keç',
    'auth.loading':     'Yüklənir...',
    'auth.or':          'və ya',
    'auth.google':      'Google ilə davam et',
    'auth.noAcc':       'Hesabınız yoxdur?',
    'auth.hasAcc':      'Hesabınız var?',
    'auth.regLink':     'Qeydiyyat',
    'auth.loginLink':   'Daxil ol',
    /* Auth errors */
    'err.emailUsed':    'Bu e-poçt artıq istifadə olunur.',
    'err.invalidEmail': 'E-poçt formatı səhvdir.',
    'err.weakPass':     'Şifrə ən az 6 simvol olmalıdır.',
    'err.noUser':       'Bu e-poçtla hesab tapılmadı.',
    'err.wrongPass':    'Şifrə yanlışdır.',
    'err.invalidCred':  'E-poçt və ya şifrə səhvdir.',
    'err.tooMany':      'Çox cəhd edildi. Bir az gözləyin.',
    'err.network':      'Şəbəkə xətası.',
    'err.popup':        'Giriş ləğv edildi.',
    'err.generic':      'Xəta baş verdi. Yenidən cəhd edin.',
    /* Search */
    'search.title':     'Axtarış nəticələri',
    'search.found':     'nəticə tapıldı',
    'search.none':      'Nəticə tapılmadı',
    'search.stores':    'Mağazalar',
    'search.byCat':     'Kateqoriya üzrə',
    'search.byBrand':   'Marka üzrə',
    'search.byName':    'Məhsul adı üzrə',
    'search.products':  'məhsul',
    'search.goto':      'Mağazaya keç →',
    /* Store page */
    'store.followers':  'İzləyici',
    'store.products':   'Məhsul',
    'store.since':      'İldən bəri',
    'store.follow':     'İzlə',
    'store.following':  'İzləyirsiniz',
    'store.allProds':   'Məhsullar',
    'store.about':      'Haqqımızda',
    'store.campaign':   'Kampaniya',
    'store.campBadge':  'Aktiv deyil',
    'store.campTitle':  'Hazırda kampaniya yoxdur',
    'store.campDesc':   'Bu mağazanın aktiv kampaniyası olmadıqda burada görünəcək.',
    'store.contact':    'Əlaqə',
    'store.address':    'Ünvan & İş saatları',
    'store.social':     'Sosial Media',
    'store.delivery':   'Çatdırılma',
    'store.freeShip':   '✓ Pulsuz çatdırılma',
    'store.empty':      'Bu mağazada hələ məhsul yoxdur',
    /* Profile sidebar */
    'nav.overview':     'İcmal',
    'nav.myInfo':       'Məlumatlarım',
    'nav.orders':       'Sifarişlərim',
    'nav.wishlist':     'İstək siyahısı',
    'nav.addresses':    'Ünvanlarım',
    'nav.vendor':       'Satıcı paneli',
    'nav.listings':     'Elanlarım',
    'nav.logout':       'Çıxış',
    /* Profile content */
    'p.loading':        'Yüklənir...',
    'p.welcome':        'Xoş gəlmisiniz',
    'p.totalOrders':    'Ümumi sifariş',
    'p.wishlist':       'İstək siyahısı',
    'p.totalSpent':     'Ümumi xərc',
    'p.recentOrders':   'Son sifarişlər',
    'p.personalInfo':   'Şəxsi məlumatlar',
    'p.firstName':      'Ad',
    'p.lastName':       'Soyad',
    'p.email':          'E-poçt',
    'p.phone':          'Telefon',
    'p.phonePh':        '+994 XX XXX XX XX',
    'p.dob':            'Doğum tarixi',
    'p.gender':         'Cinsiyyət',
    'p.lang':           'Dil',
    'p.note':           'Qeyd',
    'p.notePh':         'Özünüz haqqında qısa məlumat...',
    'p.cancel':         'Ləğv et',
    'p.save':           'Yadda saxla',
    'p.changePass':     'Şifrəni dəyiş',
    'p.currentPass':    'Cari şifrə',
    'p.newPass':        'Yeni şifrə',
    'p.confirmPass':    'Yeni şifrəni təkrarla',
    'p.updatePass':     'Şifrəni yenilə',
    'p.noOrders':       'Hələ sifariş yoxdur.',
    'p.noWishlist':     'Bəyəndikləriniz yoxdur.',
    'p.addAddress':     'Yeni ünvan əlavə et',
    'p.addressSoon':    'Yeni ünvan funksiyası tezliklə',
    'p.saved':          'Məlumatlar yadda saxlandı ✓',
    'p.passSaved':      'Şifrə uğurla yeniləndi ✓',
    'p.passNoMatch':    'Yeni şifrələr uyğun gəlmir',
    'p.passShort':      'Şifrə ən az 6 simvol olmalıdır',
    'p.passWrong':      'Cari şifrə yanlışdır',
    'p.fillAll':        'Bütün sahələri doldurun',
    'p.nameEmpty':      'Ad boş ola bilməz.',
    /* Gender options */
    'gender.female':    'Qadın',
    'gender.male':      'Kişi',
    'gender.notSay':    'Qeyd etmək istəmirəm',
    /* Vendor badge */
    'vendor.new':       'Yeni',
    'vendor.pending':   'Baxılır',
    'vendor.active':    'Aktiv',
    'vendor.rejected':  'Rədd',
    /* Order status */
    'order.delivered':  'Çatdırıldı',
    'order.shipped':    'Yolda',
    'order.pending':    'Hazırlanır',
    'order.cancelled':  'Ləğv edildi',
    /* Toast */
    'toast.welcome':    'Xoş gəldiniz! 👋',
    'toast.registered': 'Qeydiyyat uğurlu oldu! 🎉',
    'toast.google':     'Google ilə giriş uğurlu oldu! 🎉',
    'toast.deleted':    'Elan silindi',
    'toast.addrDel':    'Ünvan silindi',
    'toast.wishDel':    'Məhsul silindi',
    'toast.cartAdded':  'Səbətə əlavə edildi ✓',
    /* Index page */
    'idx.collection':   'Yeni Kolleksiya',
  },

  /* ══════════════ РУССКИЙ ══════════════ */
  ru: {
    'header.search':    'Поиск товаров, брендов или категорий...',
    'header.signin':    'Войти',
    'header.wishlist':  'Список желаний',
    'header.cart':      'Корзина',
    'strip.text':       '🚚 <span>50 AZN</span> — бесплатная доставка &nbsp;|&nbsp; Новая коллекция уже здесь ✨',
    'footer.tagline':   'Откройте для себя новейшие тренды моды.<br>Качество, стиль и комфорт.',
    'footer.cats':      'Категории',
    'footer.women':     'Женщины',
    'footer.men':       'Мужчины',
    'footer.kids':      'Дети',
    'footer.acc':       'Аксессуары',
    'footer.help':      'Помощь',
    'footer.delivery':  'Доставка',
    'footer.returns':   'Возврат',
    'footer.size':      'Таблица размеров',
    'footer.contact':   'Контакт',
    'footer.about':     'О нас',
    'footer.who':       'Кто мы',
    'footer.careers':   'Карьера',
    'footer.privacy':   'Конфиденциальность',
    'footer.terms':     'Условия',
    'footer.copy':      '© 2025 MODA. Все права защищены.',
    'auth.loginTitle':  'Добро пожаловать',
    'auth.regTitle':    'Регистрация',
    'auth.loginSub':    'Войдите в свой аккаунт',
    'auth.regSub':      'Создайте новый аккаунт',
    'auth.name':        'Имя Фамилия',
    'auth.namePh':      'Введите ваше имя',
    'auth.email':       'Эл. почта',
    'auth.emailPh':     'primer@mail.com',
    'auth.pass':        'Пароль',
    'auth.passPh':      '••••••••',
    'auth.loginBtn':    'Войти',
    'auth.regBtn':      'Зарегистрироваться',
    'auth.loading':     'Загрузка...',
    'auth.or':          'или',
    'auth.google':      'Продолжить с Google',
    'auth.noAcc':       'Нет аккаунта?',
    'auth.hasAcc':      'Уже есть аккаунт?',
    'auth.regLink':     'Регистрация',
    'auth.loginLink':   'Войти',
    'err.emailUsed':    'Этот e-mail уже используется.',
    'err.invalidEmail': 'Неверный формат e-mail.',
    'err.weakPass':     'Пароль должен содержать не менее 6 символов.',
    'err.noUser':       'Аккаунт с этим e-mail не найден.',
    'err.wrongPass':    'Неверный пароль.',
    'err.invalidCred':  'Неверный e-mail или пароль.',
    'err.tooMany':      'Слишком много попыток. Подождите немного.',
    'err.network':      'Ошибка сети.',
    'err.popup':        'Вход отменён.',
    'err.generic':      'Произошла ошибка. Попробуйте снова.',
    'search.title':     'Результаты поиска',
    'search.found':     'результатов найдено',
    'search.none':      'Результатов не найдено',
    'search.stores':    'Магазины',
    'search.byCat':     'По категории',
    'search.byBrand':   'По бренду',
    'search.byName':    'По названию товара',
    'search.products':  'товаров',
    'search.goto':      'Перейти в магазин →',
    'store.followers':  'Подписчики',
    'store.products':   'Товары',
    'store.since':      'На рынке с',
    'store.follow':     'Подписаться',
    'store.following':  'Вы подписаны',
    'store.allProds':   'Товары',
    'store.about':      'О магазине',
    'store.campaign':   'Кампания',
    'store.campBadge':  'Не активна',
    'store.campTitle':  'Активных кампаний нет',
    'store.campDesc':   'Когда появится активная кампания, она отобразится здесь.',
    'store.contact':    'Контакты',
    'store.address':    'Адрес и рабочие часы',
    'store.social':     'Социальные сети',
    'store.delivery':   'Доставка',
    'store.freeShip':   '✓ Бесплатная доставка',
    'store.empty':      'В этом магазине пока нет товаров',
    'nav.overview':     'Обзор',
    'nav.myInfo':       'Мои данные',
    'nav.orders':       'Мои заказы',
    'nav.wishlist':     'Список желаний',
    'nav.addresses':    'Мои адреса',
    'nav.vendor':       'Панель продавца',
    'nav.listings':     'Мои объявления',
    'nav.logout':       'Выйти',
    'p.loading':        'Загрузка...',
    'p.welcome':        'Добро пожаловать',
    'p.totalOrders':    'Всего заказов',
    'p.wishlist':       'Список желаний',
    'p.totalSpent':     'Общие расходы',
    'p.recentOrders':   'Последние заказы',
    'p.personalInfo':   'Личные данные',
    'p.firstName':      'Имя',
    'p.lastName':       'Фамилия',
    'p.email':          'Эл. почта',
    'p.phone':          'Телефон',
    'p.phonePh':        '+994 XX XXX XX XX',
    'p.dob':            'Дата рождения',
    'p.gender':         'Пол',
    'p.lang':           'Язык',
    'p.note':           'Заметка',
    'p.notePh':         'Краткая информация о себе...',
    'p.cancel':         'Отмена',
    'p.save':           'Сохранить',
    'p.changePass':     'Изменить пароль',
    'p.currentPass':    'Текущий пароль',
    'p.newPass':        'Новый пароль',
    'p.confirmPass':    'Повторите новый пароль',
    'p.updatePass':     'Обновить пароль',
    'p.noOrders':       'Заказов пока нет.',
    'p.noWishlist':     'Избранных товаров нет.',
    'p.addAddress':     'Добавить новый адрес',
    'p.addressSoon':    'Функция нового адреса скоро',
    'p.saved':          'Данные сохранены ✓',
    'p.passSaved':      'Пароль успешно обновлён ✓',
    'p.passNoMatch':    'Новые пароли не совпадают',
    'p.passShort':      'Пароль должен содержать не менее 6 символов',
    'p.passWrong':      'Текущий пароль неверен',
    'p.fillAll':        'Заполните все поля',
    'p.nameEmpty':      'Имя не может быть пустым.',
    'gender.female':    'Женщина',
    'gender.male':      'Мужчина',
    'gender.notSay':    'Не указывать',
    'vendor.new':       'Новый',
    'vendor.pending':   'На рассмотрении',
    'vendor.active':    'Активный',
    'vendor.rejected':  'Отклонён',
    'order.delivered':  'Доставлено',
    'order.shipped':    'В пути',
    'order.pending':    'Готовится',
    'order.cancelled':  'Отменён',
    'toast.welcome':    'Добро пожаловать! 👋',
    'toast.registered': 'Регистрация прошла успешно! 🎉',
    'toast.google':     'Вход через Google выполнен! 🎉',
    'toast.deleted':    'Объявление удалено',
    'toast.addrDel':    'Адрес удалён',
    'toast.wishDel':    'Товар удалён',
    'toast.cartAdded':  'Добавлено в корзину ✓',
    'idx.collection':   'Новая Коллекция',
  },

  /* ══════════════ ENGLISH ══════════════ */
  en: {
    'header.search':    'Search products, brands or categories...',
    'header.signin':    'Sign In',
    'header.wishlist':  'Wishlist',
    'header.cart':      'Cart',
    'strip.text':       '🚚 Free shipping on orders over <span>50 AZN</span> &nbsp;|&nbsp; New collection just arrived ✨',
    'footer.tagline':   'Discover the latest fashion trends.<br>Quality, style and comfort.',
    'footer.cats':      'Categories',
    'footer.women':     'Women',
    'footer.men':       'Men',
    'footer.kids':      'Kids',
    'footer.acc':       'Accessories',
    'footer.help':      'Help',
    'footer.delivery':  'Delivery',
    'footer.returns':   'Returns',
    'footer.size':      'Size Guide',
    'footer.contact':   'Contact',
    'footer.about':     'About Us',
    'footer.who':       'Who We Are',
    'footer.careers':   'Careers',
    'footer.privacy':   'Privacy',
    'footer.terms':     'Terms',
    'footer.copy':      '© 2025 MODA. All rights reserved.',
    'auth.loginTitle':  'Welcome Back',
    'auth.regTitle':    'Create Account',
    'auth.loginSub':    'Sign in to your account',
    'auth.regSub':      'Create a new account',
    'auth.name':        'Full Name',
    'auth.namePh':      'Enter your name',
    'auth.email':       'Email',
    'auth.emailPh':     'example@mail.com',
    'auth.pass':        'Password',
    'auth.passPh':      '••••••••',
    'auth.loginBtn':    'Sign In',
    'auth.regBtn':      'Create Account',
    'auth.loading':     'Loading...',
    'auth.or':          'or',
    'auth.google':      'Continue with Google',
    'auth.noAcc':       "Don't have an account?",
    'auth.hasAcc':      'Already have an account?',
    'auth.regLink':     'Register',
    'auth.loginLink':   'Sign In',
    'err.emailUsed':    'This email is already in use.',
    'err.invalidEmail': 'Invalid email format.',
    'err.weakPass':     'Password must be at least 6 characters.',
    'err.noUser':       'No account found with this email.',
    'err.wrongPass':    'Incorrect password.',
    'err.invalidCred':  'Invalid email or password.',
    'err.tooMany':      'Too many attempts. Please wait.',
    'err.network':      'Network error.',
    'err.popup':        'Login cancelled.',
    'err.generic':      'An error occurred. Please try again.',
    'search.title':     'Search Results',
    'search.found':     'results found',
    'search.none':      'No results found',
    'search.stores':    'Stores',
    'search.byCat':     'By Category',
    'search.byBrand':   'By Brand',
    'search.byName':    'By Product Name',
    'search.products':  'products',
    'search.goto':      'Visit Store →',
    'store.followers':  'Followers',
    'store.products':   'Products',
    'store.since':      'Since',
    'store.follow':     'Follow',
    'store.following':  'Following',
    'store.allProds':   'Products',
    'store.about':      'About',
    'store.campaign':   'Campaign',
    'store.campBadge':  'Inactive',
    'store.campTitle':  'No active campaigns',
    'store.campDesc':   'Active campaigns will appear here when available.',
    'store.contact':    'Contact',
    'store.address':    'Address & Hours',
    'store.social':     'Social Media',
    'store.delivery':   'Delivery',
    'store.freeShip':   '✓ Free Delivery',
    'store.empty':      'This store has no products yet',
    'nav.overview':     'Overview',
    'nav.myInfo':       'My Info',
    'nav.orders':       'My Orders',
    'nav.wishlist':     'Wishlist',
    'nav.addresses':    'My Addresses',
    'nav.vendor':       'Vendor Panel',
    'nav.listings':     'My Listings',
    'nav.logout':       'Sign Out',
    'p.loading':        'Loading...',
    'p.welcome':        'Welcome',
    'p.totalOrders':    'Total Orders',
    'p.wishlist':       'Wishlist',
    'p.totalSpent':     'Total Spent',
    'p.recentOrders':   'Recent Orders',
    'p.personalInfo':   'Personal Information',
    'p.firstName':      'First Name',
    'p.lastName':       'Last Name',
    'p.email':          'Email',
    'p.phone':          'Phone',
    'p.phonePh':        '+994 XX XXX XX XX',
    'p.dob':            'Date of Birth',
    'p.gender':         'Gender',
    'p.lang':           'Language',
    'p.note':           'Note',
    'p.notePh':         'A short description about yourself...',
    'p.cancel':         'Cancel',
    'p.save':           'Save',
    'p.changePass':     'Change Password',
    'p.currentPass':    'Current Password',
    'p.newPass':        'New Password',
    'p.confirmPass':    'Confirm New Password',
    'p.updatePass':     'Update Password',
    'p.noOrders':       'No orders yet.',
    'p.noWishlist':     'No favourites yet.',
    'p.addAddress':     'Add New Address',
    'p.addressSoon':    'New address feature coming soon',
    'p.saved':          'Information saved ✓',
    'p.passSaved':      'Password updated successfully ✓',
    'p.passNoMatch':    'New passwords do not match',
    'p.passShort':      'Password must be at least 6 characters',
    'p.passWrong':      'Current password is incorrect',
    'p.fillAll':        'Please fill in all fields',
    'p.nameEmpty':      'Name cannot be empty.',
    'gender.female':    'Female',
    'gender.male':      'Male',
    'gender.notSay':    'Prefer not to say',
    'vendor.new':       'New',
    'vendor.pending':   'Pending',
    'vendor.active':    'Active',
    'vendor.rejected':  'Rejected',
    'order.delivered':  'Delivered',
    'order.shipped':    'Shipped',
    'order.pending':    'Processing',
    'order.cancelled':  'Cancelled',
    'toast.welcome':    'Welcome! 👋',
    'toast.registered': 'Registration successful! 🎉',
    'toast.google':     'Signed in with Google! 🎉',
    'toast.deleted':    'Listing deleted',
    'toast.addrDel':    'Address deleted',
    'toast.wishDel':    'Item removed',
    'toast.cartAdded':  'Added to cart ✓',
    'idx.collection':   'New Collection',
  }
};

/* ══════════════════════════════════════════
   KÖMƏKÇI FUNKSİYALAR
══════════════════════════════════════════ */

/** Cari dili qaytar */
function getCurrentLang() {
  return localStorage.getItem('sitelang') || 'az';
}

/** Açara görə tərcümə qaytar */
function t(key) {
  const lang = getCurrentLang();
  return (LANGS[lang] && LANGS[lang][key] !== undefined)
    ? LANGS[lang][key]
    : (LANGS['az'][key] !== undefined ? LANGS['az'][key] : key);
}

/**
 * Dili dəyiş, localStorage-a yaz, UI-ı yenilə.
 * Çağıran: profile.html-dəki langField select
 */
function setLang(lang) {
  if (!LANGS[lang]) return;
  localStorage.setItem('sitelang', lang);
  applyLang();
  if (typeof renderHeader === 'function') renderHeader();
  if (typeof renderFooter === 'function') renderFooter();
}

/**
 * data-i18n atributları olan bütün elementləri yenilə.
 * Hər tab keçidindən, hər dynamic render-dən sonra çağır.
 */
function applyLang() {
  /* Mətn məzmunu */
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = t(key);
  });

  /* Placeholder */
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    el.placeholder = t(el.getAttribute('data-i18n-ph'));
  });

  /* Title atributu */
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    el.title = t(el.getAttribute('data-i18n-title'));
  });

  /* Dil seçici select-i cari dilə set et */
  const langField = document.getElementById('langField');
  if (langField) langField.value = getCurrentLang();

  /* Gender seçici option mətnlərini yenilə */
  const gf = document.getElementById('genderField');
  if (gf) {
    const map = { 'Qadın': 'gender.female', 'Kişi': 'gender.male', 'Qeyd etmək istəmirəm': 'gender.notSay' };
    [...gf.options].forEach(opt => {
      if (map[opt.value]) opt.textContent = t(map[opt.value]);
    });
  }
}

/* DOM hazır olduqda ilk tətbiq */
document.addEventListener('DOMContentLoaded', applyLang);
